from __future__ import annotations

import re

from .errors import FormatError


_TABLES = ("ITEMS_BYCID", "ITEMS_BYNAME", "ITEMS_BYSERVERID")
_SERVER_FIELD = re.compile(rb'\bserverid = "(\d+)"')
_SERVER_KEY = re.compile(rb'^\[(\d+)\] = \{')


def remove_remake_catalog_entries(
    source: bytes, target_server_ids: set[int]
) -> tuple[bytes, dict[str, int]]:
    """Drop obsolete non-pickupable item rows from the derived archive.

    Preserve every unrelated byte, including line endings and table order. The
    source archive can be regenerated by the server's generateItemArchive.
    """

    lines = source.splitlines(keepends=True)
    result: list[bytes] = []
    counts = {table: 0 for table in _TABLES}
    section: str | None = None
    seen: list[str] = []
    for line in lines:
        for table in _TABLES:
            if line.rstrip(b"\r\n") == table.encode("ascii") + b" = {":
                if table in seen or (seen and _TABLES.index(table) != len(seen)):
                    raise FormatError("ordem das tabelas do catálogo gerado mudou")
                section = table
                seen.append(table)
                break
        if section and line.rstrip(b"\r\n") == b"}":
            section = None
            result.append(line)
            continue
        if section:
            match = (
                _SERVER_KEY.match(line)
                if section == "ITEMS_BYSERVERID"
                else _SERVER_FIELD.search(line)
            )
            if match and int(match.group(1)) in target_server_ids:
                counts[section] += 1
                continue
        result.append(line)
    if seen != list(_TABLES) or section is not None:
        raise FormatError("estrutura do catálogo gerado inesperada")
    return b"".join(result), counts
